name: Python Tests

# Trigger the workflow on push and pull requests to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository's code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt  # If you have a requirements file

    # Step 4: Run tests with pytest
    - name: Run pytest
      run: |
        pytest --disable-warnings
